### ISSUE TITLE
What are the exact versions of the packages?

### ISSUE THREAD

**Issue by Yusuke196** [yukiar/CEFR-SP#3]
Dear authors, thank you for the great work.

I am having trouble with running the below command.

```
python level_estimator.py --model bert-base-cased --lm_layer 11 --seed 935 --num_labels 6 --batch 128 --warmup 0 --with_loss_weight --num_prototypes 3 --type contrastive --init_lr 1.0e-5 --alpha 0.2 --data ../CEFR-SP/SCoRE/CEFR-SP_SCoRE --test ../CEFR-SP/SCoRE/CEFR-SP_SCoRE --out ../out/
```

I suspect this is happening because package versions of my environment are different from yours.
However, the exact version of packages other than pytorch-lightning doesn't seem to be specified in `src/requirements.txt`.
Could you publish the versions of other packages such as torch as well as cuda?

**Comment by yukiar** [comment]
Thank you for your issue.
Updated the `src/requirements.txt` to add version numbers.
